# Base configs
baseurl: "https://photography.purinis.lt"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Linas Purinis"
subtitle: "See the world through my eyes!"
author: "Linas Purinis"
header:
 title: "Photography"
 subtitle: "by Linas Purinis"
footer:
 name: "Hey there, my name is Linas"
 bio: "I am a developer."
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "LP"
#social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://twitter.com/linaspurinis"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
